pins:
  - pin: 1A
    function: 12V all times
    type: 12V
  - pin: 1B
    function: ECU power in start & run
    type: 12V

  - pin: 1D
    function: CAN bus high
    type: can

  - pin: 1F
    function: CAN bus low
    type: can

  - pin: 1E
    class: outputs
    function: Check Engine Light
    type: ls

  - pin: 1G
    class: outputs
    ts_name: 1G - IGN_1
    type: ign
  - pin: 1H
    class: outputs
    ts_name: 1H - IGN_2
    type: ign

  - pin: 1I
    function: USB GND
    type: gnd

  - pin: 1J
    class: outputs
    function: A/C Relay
    type: ls

  - pin: 1L
    class: outputs
    function: Radiator Fan Relay
    type: ls

  - pin: 1N
    function: Sensor +5V

  - pin: 1Q
    class: switch_inputs
    function: A/C switch input
    type: din

  - pin: 1R
    class: outputs
    function: A/C Fan Relay
    type: ls

  - pin: 1S
    function: USB D-

  - pin: 1T
    function: USB D+

  - pin: 1V
    class: switch_inputs
    function: Clutch switch input
    type: din

  - pin: 3A
    function: Power GND
    type: pgnd
    color: white
  - pin: 3B
    function: Power GND
    type: pgnd
    color: white

  - pin: 3C
    function: Sensor GND
    type: gnd
    color: white
  - pin: 3D
    function: Sensor GND
    type: gnd
    color: white

  - pin: 3E
    class: [event_inputs]
    ts_name: 3E - CRANK
    function: Crankshaft Sensor
  - pin: 3F
    function: MAF GND
    type: gnd
    color: white

  - pin: 3G
    class: [event_inputs]
    ts_name: 3G - CAM
    function: Camshaft Sensor

  - pin: 3O
    class: analog_inputs
    ts_name: 3O - MAF
    function: VAF/MAF sensor

  - pin: 3P
    class: analog_inputs
    ts_name: 3P - IAT
    function: IAT sensor

  - pin: 3T
    class: outputs
    function: Fuel Pump Relay
    type: ls

  - pin: 3N
    class: analog_inputs
    ts_name: 3N - AFR
    function: External Wideband signal

  - pin: 3Q
    class: analog_inputs
    ts_name: 3Q - CLT
    function: CLT sensor


  - pin: 3U
    class: outputs
    ts_name: 3U - INJ_1
    function: Injector #1
    type: inj

  - pin: 3V
    class: outputs
    ts_name: 3V - INJ_2
    function: Injector #2
    type: inj

  - pin: 3W
    class: outputs
    ts_name: 3W - IDLE
    function: IAC idle
    type: ls

  - pin: 3Y
    class: outputs
    ts_name: 3Y - INJ_4
    function: Injector #3
    type: inj

  - pin: 3Z
    class: outputs
    ts_name: 3Z - INJ_4
    function: Injector #4
    type: inj

info:
  image:
    file: main.jpg
  pins:
    - pin: 1A
      x: 3984
      y: 312
    - pin: 1B
      x: 3984
      y: 512

    - pin: 1C
      x: 3860
      y: 312
    - pin: 1D
      x: 3860
      y: 512

    - pin: 1E
      x: 3735
      y: 352
    - pin: 1F
      x: 3735
      y: 544

    - pin: 1G
      x: 3624
      y: 352
    - pin: 1H
      x: 3624
      y: 544

    - pin: 1I
      x: 3508
      y: 352
    - pin: 1J
      x: 3508
      y: 544

    - pin: 1M
      x: 3284
      y: 352
    - pin: 1N
      x: 3284
      y: 544

    - pin: 1R
      x: 3062
      y: 544

    - pin: 1S
      x: 2952
      y: 352
    - pin: 1T
      x: 2952
      y: 544

    - pin: 1V
      x: 2838
      y: 512

    - pin: 3A
      x: 1604
      y: 312
    - pin: 3B
      x: 1604
      y: 512

    - pin: 3C
      x: 1488
      y: 312
    - pin: 3D
      x: 1488
      y: 512

    - pin: 3E
      x: 1368
      y: 360
    - pin: 3F
      x: 1368
      y: 552

    - pin: 3G
      x: 1256
      y: 360

    - pin: 3I
      x: 1140
      y: 360
    - pin: 3J
      x: 1140
      y: 552

    - pin: 3O
      x: 807
      y: 360
    - pin: 3P
      x: 807
      y: 552

    - pin: 3Q
      x: 690
      y: 360


    - pin: 3U
      x: 460
      y: 312
    - pin: 3V
      x: 460
      y: 512

    - pin: 3W
      x: 330
      y: 312

    - pin: 3Y
      x: 200
      y: 312
    - pin: 3Z
      x: 200
      y: 512
