outputs:
  # MCU
  GPIOH_7: "    - Self Shutdown"
  # TLE6240
  TLE6240_PIN_1:   "D17 - FAN 1"
  TLE6240_PIN_2:   "D03 - FAN 2"
  TLE6240_PIN_3:   "C16 - Tacho out"
  TLE6240_PIN_4:   "C14 - FPump modulator"
  TLE6240_PIN_5:   "D23 - FPump relay"
  TLE6240_PIN_6:   "D22 - EGR control"
  TLE6240_PIN_7:   "D19 - CE indicator"
  TLE6240_PIN_8:   "C15 - AUX1 out"
  TLE6240_PIN_9:   "D18 - Auxillary air valve"
  TLE6240_PIN_10:  "D06 - Absorber purge"
  TLE6240_PIN_11:  "D02 - IDLE open"
  TLE6240_PIN_12:  "D01 - IDLE close"
  TLE6240_PIN_13:  "XP2 - AUX0 out"
  TLE6240_PIN_14:  "XP2 - AUX1 out"
  TLE6240_PIN_15:  "B08 - AC clutch"
  TLE6240_PIN_16:  "D20 - Charge valve"
  # MC33810s
  MC33810_0_PIN_1: "D13 - INJ 1"
  MC33810_0_PIN_2: "D11 - INJ 3"
  MC33810_0_PIN_3: "A01 - INJ 5"
  MC33810_0_PIN_4: "XP2 - INJ 7"
  MC33810_0_PIN_5: "D07 - IGN 1"
  MC33810_0_PIN_6: "D09 - IGN 3"
  MC33810_0_PIN_7: "XP2 - IGN 7 (HP)"
  MC33810_0_PIN_8: "D21 - IGN 5"
  MC33810_1_PIN_1: "D12 - INJ 2"
  MC33810_1_PIN_2: "D26 - INJ 4"
  MC33810_1_PIN_3: "A12 - INJ 6"
  MC33810_1_PIN_4: "XP6 - INJ 8"
  MC33810_1_PIN_5: "XP6 - IGN 8 (HP)"
  MC33810_1_PIN_6: "D16 - IGN 6"
  MC33810_1_PIN_7: "D08 - IGN 2"
  MC33810_1_PIN_8: "D10 - IGN 4"

switch_inputs:
  MC33972_PIN_1:  "TP  - SP1 Din"
  MC33972_PIN_2:  "TP  - SP2 Din"
  MC33972_PIN_3:  "TP  - SP3 Din"
  MC33972_PIN_5:  "C10 - Starter Din"
  MC33972_PIN_6:  "C12 - Memory SW Din"
  MC33972_PIN_7:  "C13 - Test SW Din"
  MC33972_PIN_8:  "D04 - California ID Din"
  MC33972_PIN_16: "C09 - Air Condition request Din"
  MC33972_PIN_17: "B12 - IGN Din"
  MC33972_PIN_19: "B10 - N pos Din"
  MC33972_PIN_20: "B09 - P pos Din"
  MC33972_PIN_21: "A20 - Torque Ctrl Din"
  MC33972_PIN_22: "A19 - AC Ctrl Din"

event_inputs:
  GPIOH_10: "C01 - Crank #1"
  GPIOE_9:  "A08 - Crank #2"
  GPIOH_12: "A07 - Cam"
  GPIOD_14: "B11 - Speed Din (GPIO)"
  MC33972_PIN_18: "B11 - Speed Din (MC33972)"

analog_inputs:
  EFI_ADC_0:  "TP  - AIN 0"
  EFI_ADC_1:  "int - IGN1 current"
  EFI_ADC_2:  "int - IGN2 current"
  EFI_ADC_3:  "B05 - MAF Ain"
#  EFI_ADC_4:  "n.u."
  EFI_ADC_6:  "A02 - Battery Ain"
  EFI_ADC_7:  "int - Knock"
  EFI_ADC_8:  "A05 - Oxyg #2 Ain"
  EFI_ADC_9:  "A04 - EGR t Ait"
  EFI_ADC_10: "--- - Atm P Ain"
  EFI_ADC_11: "A18 - AUX0 Ain"
  EFI_ADC_12: "B02 - TPS Ain"
  EFI_ADC_13: "int - MC33972 DIN"
  EFI_ADC_14: "A03 - Coolant t Ain"
  EFI_ADC_15: "A06 - Oxyg #1 Ain"
#  EFI_ADC3_4:  "XP2 - OPT0"
#  EFI_ADC3_5:  "n.u."
#  EFI_ADC3_6:  "n.u."
#  EFI_ADC3_7:  "n.u."
#  EFI_ADC3_8:  "n.u."
#  EFI_ADC3_9:  "XP6 - OPT3"
#  EFI_ADC3_14: "XP6 - OPT2"
#  EFI_ADC3_15: "XP2 - OPT1"
#  MC33972_PIN_4:  "A03 - Coolant t Ain"
#  MC33972_PIN_9:  "A04 - EGR t Ain"
#  MC33972_PIN_10: "A06 - Oxyg #1"
#  MC33972_PIN_11: "A05 - Oxyg #2"
#  MC33972_PIN_12: "--- - Atm P Ain"
#  MC33972_PIN_13: "A18 - AUX0 Ain"
#  MC33972_PIN_14: "B02 - TPS Ain"
#  MC33972_PIN_15: "B05 - MAF Ain"