#
# proteus board
# https://github.com/rusefi/rusefi/wiki/Hardware-Proteus-Wiring-v03
#

outputs:
  GPIOD_7:  "Lowside 1"     # pin 3/black35
  GPIOG_9:  "Lowside 2"     # pin 15/black35
  GPIOG_10: "Lowside 3"     # pin 4/black35
  GPIOG_11: "Lowside 4"     # pin 16/black35

  GPIOG_12: "Lowside 5"     # pin 5/black35
  GPIOG_13: "Lowside 6"     # pin 6/black35
  GPIOG_14: "Lowside 7"     # pin 7/black35
  GPIOB_4:  "Lowside 8"     # pin 19/black35

  GPIOB_5:  "Lowside 9"     # pin 8/black35
  GPIOB_6:  "Lowside 10"    # pin 20/black35
  GPIOB_7:  "Lowside 11"    # pin 9/black35
  GPIOB_8:  "Lowside 12"    # pin 21/black35

  GPIOB_9:  "Lowside 13"    # pin 10/black35
  GPIOE_0:  "Lowside 14"    # pin 11/black35
  GPIOE_1:  "Lowside 15"    # pin 12/black35
  GPIOE_2:  "Lowside 16"    # pin 23/black35

  GPIOD_4:  "Ign 1"         # pin 35/black35
  GPIOD_3:  "Ign 2"         # pin 34/black35
  GPIOC_9:  "Ign 3"         # pin 22/black35
  GPIOC_8:  "Ign 4"         # pin 33/black35
  GPIOC_7:  "Ign 5"         # pin 32/black35
  GPIOG_8:  "Ign 6"         # pin 31/black35
  GPIOG_7:  "Ign 7"         # pin 30/black35
  GPIOG_6:  "Ign 8"         # pin 29/black35
  GPIOG_5:  "Ign 9"         # pin 28/black35
  GPIOG_4:  "Ign 10"        # pin 27/black35
  GPIOG_3:  "Ign 11"        # pin 26/black35
  GPIOG_2:  "Ign 12"        # pin 25/black35

  GPIOA_9:  "Highside 1"    # pin 2/black35
  GPIOA_8:  "Highside 2"    # pin 1/black35
  GPIOD_15: "Highside 3"    # pin 13/black35
  GPIOD_14: "Highside 4"    # pin 14/black35

event_inputs:
  GPIOC_6:  "Digital 1"
  GPIOE_11: "Digital 2"
  GPIOE_12: "Digital 3"
  GPIOE_13: "Digital 4"
  GPIOE_14: "Digital 5"
  GPIOE_15: "Digital 6"
  GPIOE_7:  "VR 1"
  GPIOE_8:  "VR 2"

switch_inputs:
  GPIOC_6:  "Digital 1"
  GPIOE_11: "Digital 2"
  GPIOE_12: "Digital 3"
  GPIOE_13: "Digital 4"
  GPIOE_14: "Digital 5"
  GPIOE_15: "Digital 6"
  GPIOA_0: "Analog Volt 5"
  GPIOA_1: "Analog Volt 6"
  GPIOA_2: "Analog Volt 7"
  GPIOA_3: "Analog Volt 8"
  GPIOA_4: "Analog Volt 9"
  GPIOA_5: "Analog Volt 10"
  GPIOA_6: "Analog Volt 11"
  GPIOB_0: "Analog Temp 3"
  GPIOB_1: "Analog Temp 4"
  GPIOC_0: "Analog Volt 1"
  GPIOC_1: "Analog Volt 2"
  GPIOC_2: "Analog Volt 3"
  GPIOC_3: "Analog Volt 4"
  GPIOC_4: "Analog Temp 1"
  GPIOC_5: "Analog Temp 2"

analog_inputs:
  # PA0
  EFI_ADC_0: "Analog Volt 5"
  # PA1
  EFI_ADC_1: "Analog Volt 6"
  # PA2
  EFI_ADC_2: "Analog Volt 7"
  # PA3
  EFI_ADC_3: "Analog Volt 8"
  # PA4 - pin #17
  EFI_ADC_4: "Analog Volt 9"
  # PA5 - pin #28 WBO AFR
  EFI_ADC_5: "Analog Volt 10"
  # PA6 - pin #18
  EFI_ADC_6: "Analog Volt 11"
  # PA7
  EFI_ADC_7: "Battery Sense"
  # CLT, PB0, pin #20
  EFI_ADC_8: "Analog Temp 3"
  # PB1, pin #31
  EFI_ADC_9: "Analog Temp 4"
  # MAP = Analog volt 1 = PC0
  EFI_ADC_10: "Analog Volt 1"
  # TPS = Analog volt 2 = PC1
  EFI_ADC_11: "Analog Volt 2"
  # PC2
  EFI_ADC_12: "Analog Volt 3"
  # PC3
  EFI_ADC_13: "Analog Volt 4"
  # PC4
  EFI_ADC_14: "Analog Temp 1"
  # IAT = Analog Temp 2 = PC5
  EFI_ADC_15: "Analog Temp 2"
