#
# Hellen72 board
# https://rusefi.com/s/hellen72
#

outputs:
  # injector channels
  GPIOG_7: "2A - INJ_1"
  GPIOG_8: "2D - INJ_2"
  GPIOD_11: "2G - INJ_3"
  GPIOD_10: "2J - INJ_4"
  GPIOD_9: "2C - AC Fan / INJ_5"
  GPIOF_12: "2N - VTSC / INJ_6"
  GPIOF_13: "3C - Purge Solenoid / INJ_7"
  GPIOF_14: "3D - EGR Solenoid / INJ_8"
  # ignition outputs (5v)
  GPIOI_8: "3F - IGN_1 (1&4)"
  GPIOE_5: "3I - IGN_2 (2&3)"
  GPIOE_4: "2O - IGN_3"
  GPIOE_3: "3N - IGN_4"
  GPIOE_2: "3Z - IGN_5 / GNDA"
  GPIOI_5: "4K - IGN_6 / +5V_MAP"
  GPIOI_6: "3L - IGN_7 / AFR"
  GPIOI_7: "4U - IGN_8 / MAP2"

  # low-side outputs
  GPIOI_2:  "3H - MAIN (O1)"
  GPIOH_13: "3U - AWARN (O2)"
  GPIOH_14: "3J - O2H (O3)"
  GPIOH_15: "2K - AC (O4)"
  GPIOI_0:  "4R - VVT (O5)"
  GPIOA_9:  "3P - O2H2 (O7)"
  GPIOG_2:  "2M - FPUMP (O9)"
  GPIOG_3:  "3E - CANIST (O10)"
  GPIOG_4:  "2R - CE (O11)"
  GPIOC_6:  "2F - COIL_A1 (PWM1)"
  GPIOC_7:  "2E - COIL_A2 (PWM2)"
  GPIOC_8:  "2I - COIL_B1 (PWM3)"
  GPIOC_9:  "2H - COIL_B2 (PWM4)"
  GPIOD_14: "2Q - IDLE (PWM5)"
  GPIOD_15: "3M - ALTERN (PWM6)"
  GPIOD_13: "3O - TACH (PWM7)"
  GPIOD_12: "2B - ECF (PWM8)"

event_inputs:
  GPIOA_6:  "3V - CAM (A19)"
  GPIOB_1:  "3Y - CRANK (A24)"
  GPIOF_11: "3T - VSS (D5)"

switch_inputs:
  GPIOA_2: "4H - Neutral/AUX2 (A21)"
  GPIOA_0: "4I - Clutch/AUX3 (A22)"
  GPIOA_1: "4B - Brake/RES1 (A15)"
  GPIOA_3: "4C - Steering/RES2 (A16)"

analog_inputs:
  EFI_ADC_0: "4P - CLT (A13)"
  EFI_ADC_1: "4N - IAT (A14)"
  EFI_ADC_2: "4B - RES1/Brake (A15)"
  EFI_ADC_3: "4C - RES2/Steering (A16)"
  EFI_ADC_4: "4V - TPS (A17)"
  EFI_ADC_5: "4AB - FTP/PPS (A18)"
  EFI_ADC_6: "3V - CAM (A19)"
  EFI_ADC_7: "4J - VTCS/AUX4 (A20)"
  EFI_ADC_8: "4F - AC_PRES/AUX1 (A23)"
  EFI_ADC_9: "3Y - CRANK (A24)"
  EFI_ADC_10: "4X - MAF (A9)"
  EFI_ADC_11: "4U - MAP2/Ign8 (A10)"
  EFI_ADC_12: "4W - O2S (A11)"
  EFI_ADC_13: "4AA - O2S2 (A12)"
  EFI_ADC_14: "4H - AUX2/Neutral (A21)"
  EFI_ADC_15: "4I - AUX3/Clutch (A22)"
