pins:
  - pin: J6
    id: GPIOE_0
    class: outputs
    ts_name: AUX J6 PE0

  - pin: J10
    id: GPIOE_6
    class: outputs
    function: TIM9_CH2
    ts_name: AUX J10 PE6

  - pin: J11
    id: GPIOE_5
    class: outputs
    function: TIM9_CH1
    ts_name: AUX J11 PE5

  - pin: J18
    id: GPIOB_7
    class: outputs
    ts_name: AUX J18 PB7

info:
  image:
    file: pads.jpg
  pins:
    - pin: J6
      x: 42
      y: 121
    - pin: J10
      x: 184
      y: 389
    - pin: J11
      x: 184
      y: 334
    - pin: J18
      x: 161
      y: 31
