name: Unit Test CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Discover cores
      run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'

    - name: Generate Configs
      working-directory: ./firmware/
      run: bash gen_config_default.sh

    - name: Generate Live Documentation
      working-directory: ./firmware/
      run: bash gen_live_documentation.sh

    - name: Install gcc8
      run: sudo apt-get install -y gcc-8

    - name: Print GCC version
      working-directory: .
      run: gcc -v

    - name: Build Tests
      working-directory: ./unit_tests/
      run: make -j4
      
    - name: Run Tests
      run: ./unit_tests/build/rusefi_test

    - name: Install Coverage Tools
      run: sudo apt-get install ncftp lcov

    - name: Generate Code Coverage
      working-directory: ./unit_tests/
      run: ./ci_gcov.sh ${{ secrets.RUSEFI_DOXYGEN_FTP_USER }} ${{ secrets.RUSEFI_DOXYGEN_FTP_PASS }} ${{ secrets.RUSEFI_FTP_SERVER }}
