name: Generate documentation

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install ncftp, kicad, xvfb, and doxygen
      run: |
        sudo add-apt-repository ppa:js-reynaud/kicad-5.1
        sudo apt-get update
        sudo apt-get install ncftp kicad doxygen xvfb

    - name: Set FTP variables
      run: |
        if [ "${{github.event_name}}" = "push" ] && [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "name=RUSEFI_FTP_SERVER::${{secrets.RUSEFI_FTP_SERVER}}" >> $GITHUB_ENV;
          echo "name=RUSEFI_DOXYGEN_FTP_USER::${{secrets.RUSEFI_DOXYGEN_FTP_USER}}" >> $GITHUB_ENV;
          echo "name=RUSEFI_DOXYGEN_FTP_PASS::${{secrets.RUSEFI_DOXYGEN_FTP_PASS}}" >> $GITHUB_ENV;
        fi

    - name: Generate documentation
      run: xvfb-run bash ./misc/jenkins/generate_doxygen/gen_upload_docs.sh
